# requirements.yml for pip-audit testing
# Only include one version per package to avoid conflicts

dependencies:
  - flask==0.5
  - django==1.2
  - cryptography==2.1.4
  - urllib3==1.25.2
  - jinja2==2.7.2
  - insecure-package==0.1.0
